
spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: csucoderlee
    url: jdbc:mysql://127.0.0.1:3306/springinaction?characterEncoding=utf8&useSSL=true

  profiles:
    active: dev
#  http:
#    converters:
#      preferred-json-mapper: jackson
mybatis:
  mapper-locations: classpath:mapper/*.xml
